export const secretaryStats = [
  {
    _id: 'patients',
    title: 'סך החולים',
    value: '1,247 חולים',
    iconKey: 'patients',
    color: '#6155F5',
    backgroundColor: '#6155F514',
    date: 'מאז 9 ביולי 2025',
  },
  {
    _id: 'doctors',
    title: 'רופאים פעילים',
    value: '8 רופאים',
    iconKey: 'doctors',
    color: '#11D057',
    backgroundColor: '#EFFCF4',
    date: 'מאז 22 באוקטובר 2025',
  },
  {
    _id: 'requests',
    title: 'בקשות חדשות',
    value: '15 בקשות',
    iconKey: 'requests',
    color: '#EA580C',
    backgroundColor: '#FFEDD5',
    date: 'מאז 15 בדצמבר 2025',
  },
  {
    _id: 'appointments',
    title: 'הזמנות היום',
    value: '24 הזמנות',
    iconKey: 'appointments',
    color: '#0088FF',
    backgroundColor: '#EAF4FF',
    date: 'מאז 9 ביולי 2025',
  },
];
export const secretaryPatientsStats = [
  {
    _id: 'patients',
    title: 'סך החולים',
    value: '1,247 חולים',
    iconKey: 'patients',
    color: '#6155F5',
    backgroundColor: '#6155F514',
    date: 'מאז 9 ביולי 2025',
  },
  {
    _id: 'activePatients',
    title: 'חולים פעילים',
    value: '1,089 חולים',
    iconKey: 'activePatients',
    color: '#11D057',
    backgroundColor: '#EFFCF4',
    date: 'מאז 22 באוקטובר 2025',
  },
  {
    _id: 'meetingsToday',
    title: 'פגישות היום',
    value: '7 בקשות',
    iconKey: 'meetingsToday',
    color: '#EA580C',
    backgroundColor: '#FFEDD5',
    date: 'מאז 15 בדצמבר 2025',
  },
  {
    _id: 'pendingAppointment',
    title: 'פגישה ממתינה',
    value: '5 הזמנות',
    iconKey: 'pendingAppointment',
    color: '#0088FF',
    backgroundColor: '#EAF4FF',
    date: 'מאז 9 ביולי 2025',
  },
];
